<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sales_target_model extends CI_Model
{

    public $table = 'sales_target';
    public $id = 'npp';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('npp,year,month,productID,target,realisasi');
        $this->datatables->from('sales_target');
        //add this line for join
        //$this->datatables->join('table2', 'sales_target.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('sales_target/read/$1'),'Read')." | ".anchor(site_url('sales_target/update/$1'),'Update')." | ".anchor(site_url('sales_target/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'npp');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('npp', $q);
	$this->db->or_like('target', $q);
	$this->db->or_like('realisasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('npp', $q);
	$this->db->or_like('target', $q);
	$this->db->or_like('realisasi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sales_target_model.php */
/* Location: ./application/models/Sales_target_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-09 04:37:01 */
/* http://harviacode.com */